This is a prelim PR to switch to the new download service
Project-Sustain/sustain-download-service pull request #31
Opened 2021-11-17 03:48 UTC by honeybadgerofdoom

2021-11-18 02:27 UTC, drg101 requested changes
Seems like there are a lot of places where the code quality could be improved with type annotations. Try to avoid using `any` (for the most part, of course some functions will need different treatment).

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/DatasetArea/DatasetTable.tsx
> +    const [filteredDatasets, setFilteredDatasets] = useState(props.data.currentState.datasets);
type annotations needed on these `useState`

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/DatasetArea/DatasetTable.tsx
> +    function renderDatasetRows() {
why is this function below the return statements?

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/DatasetArea/DownloadDatasetPopup.tsx
> +export default function DownloadDatasetPopup(props: any) {
`any` type should be changed

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/DatasetArea/DownloadDatasetPopup.tsx
> +            tags.push(makeTag("This dataset is temporal, and will have multiple records per entry.", <HourglassEmptyIcon />))
grammar

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/DatasetArea/TableHeader/CountyDropdown.tsx
> +export default function CountyDropdown(props: any) {
`any` type

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/DatasetArea/TableHeader/DatasetFilter.tsx
> +export default function DatasetFiler(props: any) {
`any` type

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/MapArea/Filtering/FilterByStateName.tsx
> +function stateMatch(matchString: any, state: any) {
`any` types

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/MapArea/Filtering/FilterType.tsx
> +export default function FilterType(props: any) {
`any`

2021-11-18 02:27 UTC, drg101 commented on src/components/NewDataDownload/Utils/utils.tsx
> +export function lowercaseArray(array: string[]) {
Very nitpicky, but it seems like alot of the for loops in this file should be replaced with `.map` or `for of` loops.

2021-11-18 02:27 UTC, drg101 commented on src/library/CountyMapping.tsx
> +    "Alaska" : [
This file seems redundant.

2021-11-18 02:27 UTC, drg101 commented on src/library/d3.min.js
> +// https://d3js.org v6.5.0 Copyright 2021 Mike Bostock
Can this go under a /third-party directory?

2021-11-18 02:30 UTC, drg101 commented
It seems like the collection names are being auto-generated, you should be using the names from the aperture JSON, and then falling back on generating capitalized versions of the names.

2021-11-18 02:32 UTC, drg101 commented
"Include Geospatial Data" should only be an option on collections which there is a separate collection for the geospatial data (such as neon, census tracts, and counties). Right now it seems to be an option on all datasets.

2021-11-18 02:34 UTC, drg101 commented
Functionality and looks are very solid though, great job on this. I just want to make sure that people in the future can edit this code fairly easily by including high-quality type annotations.

2021-11-18 23:41 UTC, honeybadgerofdoom commented on src/components/NewDataDownload/Utils/utils.tsx
> +export function lowercaseArray(array: string[]) {
Good call - I refactored all of this.

2021-11-18 23:43 UTC, honeybadgerofdoom commented on src/library/gisInfo.js
> +export const gisStateCounty = {
We actually do need this file.

2021-11-18 23:43 UTC, honeybadgerofdoom commented on src/library/CountyMapping.tsx
> +    "Alaska" : [
Remove this.

2021-11-18 23:44 UTC, honeybadgerofdoom commented on src/components/NewDataDownload/DatasetArea/DownloadDatasetPopup.tsx
> +            tags.push(makeTag("This dataset is temporal, and will have multiple records per entry.", <HourglassEmptyIcon />))
Fixed

2021-11-18 23:44 UTC, honeybadgerofdoom commented on src/components/NewDataDownload/DatasetArea/DatasetTable.tsx
> +    function renderDatasetRows() {
Fixed this.

2021-11-18 23:44 UTC, honeybadgerofdoom commented on src/components/NewDataDownload/DatasetArea/DatasetTable.tsx
> +    const [filteredDatasets, setFilteredDatasets] = useState(props.data.currentState.datasets);
Fixed these.

2021-11-18 23:57 UTC, honeybadgerofdoom commented on src/library/d3.min.js
> +// https://d3js.org v6.5.0 Copyright 2021 Mike Bostock
Fixed this.

2021-11-19 18:26 UTC, honeybadgerofdoom commented
> It seems like the collection names are being auto-generated, you should be using the names from the aperture JSON, and then falling back on generating capitalized versions of the names.

Good idea, I fixed this.

2021-11-19 18:38 UTC, honeybadgerofdoom commented
> "Include Geospatial Data" should only be an option on collections which there is a separate collection for the geospatial data (such as neon, census tracts, and counties). Right now it seems to be an option on all datasets.

What am I looking for in the data to make this determination? The fields I'm seeing in the collection object for Neon datasets are collection, fieldMetadata, icon, info, source, linked, temporal. Comparing this to another collection like, say, Trails Geo I only see collection and label.

2021-11-20 20:30 UTC, drg101 approved these changes
everything seems to work

2021-11-21 05:17 UTC, merged